name: unit-tests
on: [push, pull_request]
jobs:
  es5-initial:
    name: 00-es5-initial
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source files
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: cd 00-es5-initial; npm install
      - run: cd 00-es5-initial; npm test

  es5-added-lint:
    name: 01-es5-added-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source files
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: cd 01-es5-added-lint; npm install
      - run: cd 01-es5-added-lint; npm test

  es6-initial:
    name: 10-es6-initial
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source files
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: cd 10-es6-initial; npm install
      - run: cd 10-es6-initial; npm test

  es6-added-lint:
    name: 11-es6-added-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source files
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: cd 11-es6-added-lint; npm install
      - run: cd 11-es6-added-lint; npm test

  ts-initial:
    name: 20-ts-initial
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source files
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: cd 20-ts-initial; npm install
      - run: cd 20-ts-initial; npm test

  ts-added-lint:
    name: 21-ts-added-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source files
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: cd 21-ts-added-lint; npm install
      - run: cd 21-ts-added-lint; npm test

  ts-usecase-common:
    name: 22-ts-usecase-common
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source files
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: cd 22-ts-usecase-common; npm install
      - run: cd 22-ts-usecase-common; npm test

  ts-react-initial:
    name: 23-ts-react-initial
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source files
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: cd 23-ts-react-initial; npm install
      - run: cd 23-ts-react-initial; npm test

  ts-react-add-lint:
    name: 24-ts-react-add-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source files
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: cd 24-ts-react-add-lint; npm install
      - run: cd 24-ts-react-add-lint; npm test

  ts-react-testing-library:
    name: 25-ts-react-testing-library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source files
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: cd 25-ts-react-testing-library; npm install
      - run: cd 25-ts-react-testing-library; npm test
